---

# 添加monit配置文件
- name: 创建monit目录
  when: app_name is defined
  file: dest=/etc/monit.d state=directory

- name: template transfor java dir
  template: src=monit.j2 dest=/etc/monit.d/'{{ app_name }}'.conf
