---
## ------ 建立相关服务目录 ------
- name: 创建目录
  file: name={{ item }} state=directory owner={{ app_user }} group={{ app_group }}
  with_items: 
  - "{{ app_dir }}"
  - "{{ app_src }}/{{ app_name }}"
  - "{{ app_upflie }}"

- name: 获取monit配置
  when: scripts_start is defined and scripts_stop is defined
  stat: path=/etc/monit.d/{{ app_name }}.conf
  register: monitConf

- name: 获取service配置
  when: scripts_start is defined and scripts_stop is defined
  stat: path={{ scripts_path }}
  register: servicepath