---

# 查看服务信息

- name: "获取版本"
  shell: "{{ app_name}} --version 2>&1 "
  register: get_python_version
  notify: 查看版本

- name: "查看版本"
  debug: 
    msg: "{{ get_python_version.stdout_lines }}\r 使用{{ app_name }} 执行python"

- name: "输出环境变量"
  debug: 
    msg: "使用前添加{{ app_name }}环境变量: \r export PATH={{ app_path }}/{{ conda_name }}/envs/{{ app_name }}/bin:$PATH"