---

# 添加monit路径
- name: mkdir monit path
  when: app_name is defined
  file: dest={{ item }} state=directory
  with_items: 
  - /etc/monit.d

# 创建monit配置文件
- name: update monit conf
  template: src=monit.j2 dest=/etc/monit.d/{{ app_name }}.conf
  notify: reload monit

- name: reload monit
  become: True
  become_method: su
  become_user: robot
  shell: "monit reload"
  notify: monit status

# 检查服务状态
- name: monit status
  become: True
  become_method: su
  become_user: robot
  shell: "monit status {{ app_name }}|grep status"
  notify: 查看服务状态
  register: status

- name: 查看服务状态
  debug: var=status.stdout