---
- name: monit停止
  when: monitConf.stat.exists == true
  become: True
  become_method: su
  become_user: root
  shell: "monit stop {{ app_name }}"
  notify: monit status

- name: monit启动
  when: monitConf.stat.exists == true
  become: True
  become_method: su
  become_user: root
  shell: "monit start {{ app_name }}"
  notify: monit status

- name: 服务停止
  when: scripts_stop is defined and monitConf.stat.exists == false
  become: True
  become_method: su
  become_user: robot
  shell: "cd {{ scripts_path }} && sh {{ scripts_stop }}"

- name: 服务启动
  when: scripts_start is defined and monitConf.stat.exists == false
  become: True
  become_method: su
  become_user: robot
  shell: "cd {{ scripts_path }} && sh {{ scripts_start }}"