---
# --- 检测服务 ---
- name: 根据进程名称检查pid
  shell: "ps -ef|grep {{ pid_name }}|grep -v grep |awk '{if($3==1) print $2}'"
  register: result
  tags: check

- name: 输出pid号
  debug: var=result.stdout verbosity=0

- name: 根据pid查端口，系统版本为centos6*的
  when: result.stdout != None  and ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"
  shell: "ss -lnp|grep {{ result.stdout }}|awk 'NR==1 {print $4}'|awk -F':' '{print $2}'"
  register: result
  tags: check

- name: 输出port号，系统版本为centos6*的
  debug: var=result.stdout

- name: 根据pid查端口，系统版本为centos7*的
  when: result.stdout != None  and ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"
  shell: "ss -lnp|grep {{ result.stdout }}|awk 'NR==1 {print $5}'|awk -F':' '{print $2}'"
  register: result
  tags: check

- name: 输出port号，系统版本为centos7*的
  debug: var=result.stdout

- name: 无pid时
  when: result.stdout == None
  shell: echo "进程没有启动"
  register: result

- name: 无pid时输出
<<<<<<< HEAD
  debug: var=result.stdout
=======
  debug: var=result.stdout
>>>>>>> master
