---
# --- 检测服务 ---
- name: 根据进程名称检查pid
  shell: "ps -ef|grep {{ pid_name }}|grep -v grep |awk '{if($3==1) print $2}'"
  register: pidname
  tags: check
  notify: 
    - mkdir monit path
    - update monit conf

- name: 输出pid号
  when: pidname is defined
  debug: var=pidname.stdout

- name: 根据pid查端口，系统版本为centos6*的
  when: pidname.stdout is defined  and ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"
  shell: "sleep 5 ; ss -lnp|grep '{{ pidname.stdout }}'|awk '{print $4}'"
  register: c6port
  tags: check

- name: 输出端口号，系统版本为centos6*的
  when: c6port.stdout is defined
  debug: var=c6port.stdout

- name: 根据pid查端口，系统版本为centos7*的
  when: pidname.stdout is defined  and ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"
  shell: "sleep 5 ; ss -lnp|grep {{ pidname.stdout }}|awk '{print $5}'"
  register: c7port
  tags: check

- name: 输出端口号，系统版本为centos7*的
  when: c7port.stdout is defined
  debug: var=c7port.stdout
