---
# --- 检测服务 ---
- name: 服务启停
  when: app_tpye is defined
  shell: "su - {{ app_user }} -c 'cd {{ scripts_path }} && sh {{ scripts_service }} {{ app_tpye }}'"
  register: result
  tags: scripts

- name: 服务启停，停止
  when: scripts_stop is defined
  shell: "su - {{ app_user }} -c 'cd {{ scripts_path }} && sh {{ scripts_stop }}'"

- name: 服务启停，启动
  when: scripts_start is defined
  shell: "su - {{ app_user }} -c 'cd {{ scripts_path }} && sh {{ scripts_start }}'"

- name: 检查启停脚本结果
  debug: var=result.stdout
