---
# --- 检测服务 ---
- name: 服务启停
  when: app_type is defined
  #shell: "su - {{ app_user }} -c 'cd {{ scripts_path }} && sh {{ scripts_service }} {{ app_type }}'"
  shell: cd {{ scripts_path }} && sh {{ scripts_service }} {{ app_type }} become=True become_user=robot
  register: result
  tags: scripts
- debug: var=result.stdout

- name: 服务启停，停止
  when: scripts_stop is defined
  #shell: "su - {{ app_user }} -c 'cd {{ scripts_path }} && sh {{ scripts_stop }}'"
  #become: True
  #become_method: su
  #become_user: robot
  shell: "cd {{ scripts_path }} && sh {{ scripts_stop }}"  
  ignore_errors: yes

- name: 服务启停，启动
  when: scripts_start is defined
  become: True
  become_user: robot
  shell: "cd {{ scripts_path }} && sh {{ scripts_start }}"

- name: 检查启停脚本结果
  debug: var=result.stdout
