---
- name: 更新软连接
  file: src={{ app_src }}/{{ app_name }}/{{ tag_id }} dest={{ app_dir }}/{{ app_name }} group={{ app_user }} owner={{ app_user }} state=link force=yes
  tags: scripts
  register: result.output

- name: Time of last modification
  shell: date +%s
  notify:
    - monit启动
    - 服务启动

- name: flush_handlers
  meta: flush_handlers

- debug: var=result.stdout verbosity=0